http:
  port: "8000"

db:
  postgres:
    user: "rustam"
    host: "192.168.1.138"
    port: "5432"
    dbname: "cool_kids"
    sslmode: "disable"
    tables:
      user_table: "users"
      message_table: "messages"
  redis:
    host: "localhost"
    port: "6379"

    prefix:
      auth: "auth"
