http:
  port: "8000"

auth:
  salt: "sdas8912moksa09"
  sign_key: "amerikasad"
  token_ttl: 72h

db:
  postgres:
    user: "rustam"
    password: "1234"
    host: "localhost"
    port: "5432"
    dbname: "rustam"
    sslmode: "disable"
    tables:
      user_table: "users"
      message_table: "messages"
  redis:
    host: "localhost"
    port: "6379"

    prefix:
      auth: "auth"
