http:
  port: "8000"

auth:
  salt: "sdgfuhbjniklrthgjikutgrfdikjol;,./m rtdfgcvbsxjik;m l,./thrfgvbcdytghfcvdjm ikl;,./tyfghvbcd j;m kl,./"
  sign_key: "asdjikm,lo ;.45rtegujioklertdfscgvxujn iklm,.cfghtv/bdrsxrtdfgcbvujn iklm,./"
  token_ttl: 72h

db:
  postgres:
    user: "rustam"
    password: "1234"
    host: "localhost"
    port: "5432"
    dbname: "rustam"
    sslmode: "disable"
    tables:
      user_table: "users"
      message_table: "messages"
  redis:
    host: "localhost"
    port: "6379"

    prefix:
      auth: "auth"
